# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='specialists', verbose_name='Фотография')),
                ('desc_short', models.CharField(blank=True, max_length=120, null=True, verbose_name='Заголовок описания')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Подробное описание специалиста')),
            ],
        ),
    ]
