# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0002_auto_20171125_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='specialists', verbose_name='Фотография'),
        ),
    ]
