# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20171201_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=120, null=True, verbose_name='Заголовок новостей')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст новостей')),
                ('img', models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Изображение новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
