# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Использовать'),
        ),
    ]
