# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Methodics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название методики')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('active', models.BooleanField(default=True, verbose_name='Использовать')),
            ],
        ),
    ]
