# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodics',
            options={'verbose_name': 'Методика', 'verbose_name_plural': 'Методики'},
        ),
        migrations.AddField(
            model_name='methodics',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
