# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodics', '0002_auto_20171126_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodics',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, null=True, unique=True),
        ),
    ]
