# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodics', '0003_auto_20171128_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodics',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='methodics'),
        ),
    ]
