# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methodics', '0004_methodics_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodics',
            options={'verbose_name': 'Наши услуги', 'verbose_name_plural': 'Наши услуги'},
        ),
    ]
