# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, unique=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Название услуги')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость')),
                ('active', models.BooleanField(default=True, verbose_name='Использовать')),
            ],
        ),
    ]
