# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0004_auto_20171126_1243'),
        ('price', '0002_consultprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultprice',
            name='serviceprice_ptr',
        ),
        migrations.RemoveField(
            model_name='consultprice',
            name='specialist',
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specialist.Specialist', verbose_name='Специалист'),
        ),
        migrations.DeleteModel(
            name='ConsultPrice',
        ),
    ]
