# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_auto_20171128_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprice',
            name='consult',
            field=models.BooleanField(default=False, verbose_name='Консультация'),
        ),
    ]
