# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_serviceprice_consult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprice',
            options={'verbose_name': 'Услуги - Цены', 'verbose_name_plural': 'Услуги - Цены'},
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='number',
            field=models.PositiveIntegerField(blank=True, unique=True, verbose_name='Порядковый номер (уникален)'),
        ),
    ]
