# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_auto_20171213_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprice',
            name='number',
        ),
    ]
